# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ChatMessage.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'ChatMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x43hatMessage.proto\x12\x13\x43hatMessageResponse\"\xf8\x01\n\x13\x43hatMessageResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\x03 \x01(\t\x12\r\n\x05\x64\x62_id\x18\x04 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x01\x12\x0c\n\x04type\x18\x07 \x01(\t\x12\x0b\n\x03\x61lt\x18\x08 \x01(\t\x12\r\n\x05likes\x18\t \x01(\x05\x12\r\n\x05liked\x18\n \x01(\x08\x12\x10\n\x08\x65\x64itable\x18\x0b \x01(\x08\x12\x14\n\x0cshow_buttons\x18\x0c \x01(\x08\x12\x16\n\x0e\x63ustom_buttons\x18\r \x01(\t\"s\n\x14MessagesListResponse\x12:\n\x08messages\x18\x01 \x03(\x0b\x32(.ChatMessageResponse.ChatMessageResponse\x12\r\n\x05total\x18\x02 \x01(\x05\x12\x10\n\x08has_more\x18\x03 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChatMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATMESSAGERESPONSE']._serialized_start=43
  _globals['_CHATMESSAGERESPONSE']._serialized_end=291
  _globals['_MESSAGESLISTRESPONSE']._serialized_start=293
  _globals['_MESSAGESLISTRESPONSE']._serialized_end=408
# @@protoc_insertion_point(module_scope)
